name: pizza_app_admin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  url_strategy: ^0.3.0
  font_awesome_flutter: ^10.7.0


  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

